name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
      fail-fast: true
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xserver-xorg-core xserver-xorg-video-dummy x11-utils
      - name: Configure Xorg dummy display
        run: |
          sudo bash -c 'cat > /etc/X11/xorg.conf <<EOF
          Section "Device"
              Identifier "dummy_device"
              Driver "dummy"
          EndSection
          Section "Monitor"
              Identifier "dummy_monitor"
              HorizSync 28.0-80.0
              VertRefresh 48.0-75.0
          EndSection
          Section "Screen"
              Identifier "dummy_screen"
              Device "dummy_device"
              Monitor "dummy_monitor"
              DefaultDepth 24
              SubSection "Display"
                  Depth 24
                  Modes "1920x1080"
              EndSubSection
          EndSection
          Section "ServerLayout"
              Identifier "dummy_layout"
              Screen "dummy_screen"
          EndSection
          EOF'
      - name: Start Xorg
        run: Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile /tmp/xorg.log -config /etc/X11/xorg.conf :99 &
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Export logo
        run: ./scripts/export.sh
